//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OHDR.WebServicePuller {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://omanexpo.com/soap/WebService", ConfigurationName="WebServicePuller.WebServicePortType")]
    public interface WebServicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://localhost/WebServiceSOAP/Server.php?wsdl) of message get_messageRequest does not match the default value (http://omanexpo.com/soap/WebService)
        [System.ServiceModel.OperationContractAttribute(Action="http://omanexpo.com/registration/WebServiceSOAP/server.php/get_message", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        OHDR.WebServicePuller.get_messageResponse get_message(OHDR.WebServicePuller.get_messageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://omanexpo.com/registration/WebServiceSOAP/server.php/get_message", ReplyAction="*")]
        System.Threading.Tasks.Task<OHDR.WebServicePuller.get_messageResponse> get_messageAsync(OHDR.WebServicePuller.get_messageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_message", WrapperNamespace="http://localhost/WebServiceSOAP/Server.php?wsdl", IsWrapped=true)]
    public partial class get_messageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string token;
        
        public get_messageRequest() {
        }
        
        public get_messageRequest(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_messageResponse", WrapperNamespace="http://localhost/WebServiceSOAP/Server.php?wsdl", IsWrapped=true)]
    public partial class get_messageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public get_messageResponse() {
        }
        
        public get_messageResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePortTypeChannel : OHDR.WebServicePuller.WebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePortTypeClient : System.ServiceModel.ClientBase<OHDR.WebServicePuller.WebServicePortType>, OHDR.WebServicePuller.WebServicePortType {
        
        public WebServicePortTypeClient() {
        }
        
        public WebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OHDR.WebServicePuller.get_messageResponse OHDR.WebServicePuller.WebServicePortType.get_message(OHDR.WebServicePuller.get_messageRequest request) {
            return base.Channel.get_message(request);
        }
        
        public string get_message(string token) {
            OHDR.WebServicePuller.get_messageRequest inValue = new OHDR.WebServicePuller.get_messageRequest();
            inValue.token = token;
            OHDR.WebServicePuller.get_messageResponse retVal = ((OHDR.WebServicePuller.WebServicePortType)(this)).get_message(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OHDR.WebServicePuller.get_messageResponse> OHDR.WebServicePuller.WebServicePortType.get_messageAsync(OHDR.WebServicePuller.get_messageRequest request) {
            return base.Channel.get_messageAsync(request);
        }
        
        public System.Threading.Tasks.Task<OHDR.WebServicePuller.get_messageResponse> get_messageAsync(string token) {
            OHDR.WebServicePuller.get_messageRequest inValue = new OHDR.WebServicePuller.get_messageRequest();
            inValue.token = token;
            return ((OHDR.WebServicePuller.WebServicePortType)(this)).get_messageAsync(inValue);
        }
    }
}
